export const GET_GLOBAL_PERMISSIONS = 'GET_GLOBAL_PERMISSIONS';
export const GET_GLOBAL_PERMISSIONS_SUCCESS = 'GET_GLOBAL_PERMISSIONS_SUCCESS';
export const GET_GLOBAL_PERMISSIONS_ERROR = 'GET_GLOBAL_PERMISSIONS_ERROR';
export const GET_USER_PERMISSIONS = 'GET_USER_PERMISSIONS';
export const GET_USER_PERMISSIONS_ERROR = 'GET_USER_PERMISSIONS_ERROR';
export const GET_USER_PERMISSIONS_SUCCESS = 'GET_USER_PERMISSIONS_SUCCESS';
